### ISSUE TITLE
No fieldLabelModifier in options

### ISSUE THREAD

**Issue by akegalj** [eskimor/purescript-argonaut-generic-codecs#2] opened 2016-07-14 08:27 UTC
Haskell's `aeson` contains https://hackage.haskell.org/package/aeson-0.11.2.0/docs/Data-Aeson-TH.html#v:fieldLabelModifier in its `Options` but I can't find it in https://github.com/eskimor/purescript-argonaut-generic-codecs/blob/purescript-argonaut-generic-codec/src/Data/Argonaut/Generic/Options.purs#L14 . Is this by design, can I somehow emulate `fieldLabelModifier` ?

EDIT: should I use `userEncodin`/`userDecoding` and https://github.com/purescript/purescript-generics/blob/master/src/Data/Generic.purs#L232 `recLabel` ?

**Comment by eskimor** [comment] 2016-07-14 20:42
It is not by design - I only implemented the options necessary to get an encoding compatible to aeson's default encoding, because this is what I needed for my own project.

A PR implementing this option would definitely be welcome! ;-)

You could use userEncoding/userDecoding, after some thinking - yeah they should work just fine, just provide an additional alternative matching records and doing your transformation.

**Comment by eskimor** [comment] 2016-07-14 20:44
Huh - also some hint if you are going to use this library together with purescript-bridge - you need the master branch of purescript-bridge. The last released version still uses the never merged PR to purescript-argonaut-codecs.

Yeah - I should release a new version - going on my todo list.

**Comment by akegalj** [comment] 2016-07-14 22:02
Thanks for this tip. We are using `purescript-bridge` but didn't know about this. We are going to bump it now.

**Comment by eskimor** [comment] 2016-07-15 09:26
Great! If you experience any issues - report them - I am glad if the libraries are getting better. Also PRs are very welcome. Also now that I know that there are actual users we will be more careful about backwards compatibility and will write better release announcements ;-)

**Closed as completed** 2017-03-20 13:31 UTC
Labels: enhancement, help wanted
